### ISSUE TITLE
acceptFileTypes, imageTypes:

### ISSUE THREAD

**Issue by Menogus** [tomitrescak/meteor-uploads#60]
node version 0.12.0
when i put on node server this configuration:
        acceptFileTypes: /.(gif|jpg|png)$/i,
        imageTypes: /.(gif|jpg|png)$/i,
        imageVersions: {thumbnailBig: {width: 280, height: 280}, thumbnailSmall: {width: 200, height: 200}}
i has some errors:
.....................................................................
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at ServerResponse.res.write (/home/menog/bundle/programs/server/npm/webapp/node_modules/connect/lib/middleware/compress.js:110:17)
    at ServerResponse.res.end (/home/menog/bundle/programs/server/npm/webapp/node_modules/connect/lib/middleware/compress.js:116:14)
    at [object Object].handleResult [as callback] (packages/tomi:upload-server/upload_server.js:159:1)
    at IncomingForm.finish (packages/tomi:upload-server/upload_server.js:315:1)
    at IncomingForm.emit (events.js:104:17)
    at IncomingForm._maybeEnd (/home/menog/bundle/programs/server/npm/tomi:upload-server/node_modules/formidable/lib/incoming_form.js:551:8)
    at /home/menog/bundle/programs/server/npm/tomi:upload-server/node_modules/formidable/lib/incoming_form.js:229:12
    at WriteStream.<anonymous> (/home/menog/bundle/programs/server/npm/tomi:upload-server/node_modules/formidable/lib/file.js:70:5)
    at WriteStream.g (events.js:199:16)

.....................................................................
without this 3 lines - all work perfect.

**Comment by tomitrescak** [comment]
Why are you specifying regular expressions? It all should be strings.

**Comment by Menogus** [comment]
where?
i have at server: 
Meteor.startup(function () {
    UploadServer.init({
        tmpDir: process.env.PWD + '/.uploads/tmp',
        uploadDir: process.env.PWD + '/.uploads/',
        maxFileSize: 2000000,
        checkCreateDirectories: true,
        acceptFileTypes: /.(gif|jpg|png)$/i,
        imageTypes: /.(gif|jpg|png)$/i,
        imageVersions: {thumbnailBig: {width: 280, height: 280}, thumbnailSmall: {width: 200, height: 200}}
    })
});

and at client: html: {{> upload_bootstrap callbacks=myCallbacks }}>
and at client js:
Template.staffEdit.helpers ({
    myCallbacks: function() {
        return  finished: function(index, fileInfo, context) {}
})

**Comment by Menogus** [comment]
errors becoming after error in:
maxFileSize: 2000000, - if filesize > 2mb
acceptFileTypes: /.(gif|jpg|png)$/i, if i upload somethink not like jpg/gif/png
imageVersions: {thumbnailBig: {width: 280, height: 280}, thumbnailSmall: {width: 200, height: 200}}* : when i upload image for resizeing

in meteor test its all ok
trouble with publish it on nodejs server

**Comment by Menogus** [comment]
now i delete all!!

html now: {{> upload_bootstrap}}
js now: 

if (Meteor.isServer) {
  Meteor.startup(function () {
      UploadServer.init({
          tmpDir: process.env.PWD + '/.uploads/tmp',
          uploadDir: process.env.PWD + '/.uploads/',
          maxFileSize: 2000000,
          checkCreateDirectories: true
      });
  });
}


in meteor its all ok
in nodejs server after i upload more than 2mb - error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at ServerResponse.res.write (/home/menog/bundle/programs/server/npm/webapp/node_modules/connect/lib/middleware/compress.js:110:17)
    at ServerResponse.res.end (/home/menog/bundle/programs/server/npm/webapp/node_modules/connect/lib/middleware/compress.js:116:14)
    at [object Object].handleResult [as callback] (packages/tomi:upload-server/upload_server.js:159:1)
    at IncomingForm.finish (packages/tomi:upload-server/upload_server.js:315:1)
    at IncomingForm.emit (events.js:104:17)
    at IncomingForm._maybeEnd (/home/menog/bundle/programs/server/npm/tomi:upload-server/node_modules/formidable/lib/incoming_form.js:551:8)
    at /home/menog/bundle/programs/server/npm/tomi:upload-server/node_modules/formidable/lib/incoming_form.js:229:12
    at WriteStream.<anonymous> (/home/menog/bundle/programs/server/npm/tomi:upload-server/node_modules/formidable/lib/file.js:70:5)
    at WriteStream.g (events.js:199:16)

mb its trouble with node 0.12.0 ?

i done this by:
         meteor build uploader.tar.gz
then copy to nodejs server /home/menog/bundle
then 
         cd /home/menog/bundle/programs/server/
         npm install fibers@1.0.5
         npm install underscore
         npm install source-map-support
         npm install semver
then
         cd /home/menog/bundle/
         node main.js
and it is all.
mb i forgot something for errors by your uploader?

**Comment by Menogus** [comment]
i tested it on node 0.10.36
it's all work!!!
and without warnings like:
".write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead."
so...plz make it normally work on 0.12.0 !:)

**Comment by Menogus** [comment]
so, can I count on your help with nodejs server?

**Comment by tomitrescak** [comment]
Menogus, there is no issue with the new node server, it's just a warning.

I wrote you that you should not use regular expressions but simple strings. That is exactly what you should have done:

```javascript
acceptFileTypes: '.(gif|jpg|png)'
```

and not

```javascript
acceptFileTypes: /.(gif|jpg|png)$/i, if i upload something not like jpg/gif/png
```

**Comment by Menogus** [comment]
i tested now on 0.12.0
put this configuration with all strings;

if (Meteor.isServer) {
  Meteor.startup(function () {
      UploadServer.init({
          tmpDir: process.env.PWD + '/.uploads/tmp',
          uploadDir: process.env.PWD + '/.uploads/',
          maxFileSize: '2000000',
          checkCreateDirectories: 'true',
          acceptFileTypes: '.(gif|jpg|png)'
      });
  });
}

error: 
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
/home/menog/bundle/programs/server/packages/tomi_upload-server.js:288
  } else if (!options.acceptFileTypes.test(this.name)) {
                                      ^
TypeError: undefined is not a function
    at [object Object].FileInfo.validate (packages/tomi:upload-server/upload_server.js:268:1)
    at IncomingForm.<anonymous> (packages/tomi:upload-server/upload_server.js:349:1)
    at IncomingForm.emit (events.js:110:17)
    at /home/menog/bundle/programs/server/npm/tomi:upload-server/node_modules/formidable/lib/incoming_form.js:228:12
    at WriteStream.<anonymous> (/home/menog/bundle/programs/server/npm/tomi:upload-server/node_modules/formidable/lib/file.js:70:5)
    at WriteStream.g (events.js:199:16)
    at WriteStream.emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
    at afterWrite (_stream_writable.js:362:3)
    at onwrite (_stream_writable.js:352:7)

**Comment by Menogus** [comment]
so....how i undestand you dont see this troubles on your nodejs server?
(not working acceptFileTypes / imageTypes/ imageVersions on nodejs 0.12.0 and not working  imageTypes/ imageVersions on nodejs 0.10.36)
it's a very sad, because when i tested it on meteor  - this is best package what i need
but campaign case i will go to other package then - Meteor-CollectionFS :(((

**Comment by tomitrescak** [comment]
@Menogus , these are hundreds of people using this package, no one has ever had problems with nodejs, so it's your local issue. On top of that, meteor runs its own version of node, so it does not matter which version you have installed. Different story is on deployment server though. Please download the demo application and check if you have problems there as well. If not, follow the documentation and stick to what it says, not using regular expressions instead of strings ... If you can't work it out, go with collectionfs.

**Comment by Menogus** [comment]
maybe, but maybe not, because i test you demo on meteor - its working well also with ciryllic filenames, but after i updated meteor to last version - ciryllic files was uploaded normally, but but no longer appear on http view...
and it tells about exactly that you dont update this package for new version nodejs and also meteor....

so i was try Meteor-CollectionFS and has no problem with any testing, except that I had to update mongodb :)
